name: lab01
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.4

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  url_launcher: ^6.3.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
